### ISSUE TITLE
finalize 2014 session topics

### ISSUE THREAD

**Issue by pearsonca** [pearsonca/stdio-ghana#1]
@tjhladish @jamrootz @arkerpay @dbmcpherson @seifu 

Please comment on https://github.com/pearsonca/stdio-ghana/blob/gh-pages/sessions/2014/README.md schedule arrangement.

I'll use those comments to finalize that and moving it into https://github.com/pearsonca/stdio-ghana/blob/gh-pages/sessions/2014/opening.html

**Comment by pearsonca** [comment]
Running down / around this list.  [$name] corresponds to where I put the suggested content in the course.
- What is a computer [Overview]. We covered what is a computer / what is software engineering in the overview session last year, which seemed to work fine, so I scheduled it that way again.
- Seq. Programming + Data Types [Py Var and Fun Basics] - that description sounds almost exactly like what I had in mind for Py Basics.  I think we should add basic function syntax here as well, though not yet address pass by val vs pass by ref, scope, etc.
- Flow control [Flow Control]: I originally had in mind that this would be part of Basics, but upon reflection of how students actually handled this topic, I agree it deserves its own section.
- Functions / Data Structures in Python [Py Var and Fun Adv.]: I think these can go together if we've already addressed function basics, and the details match what we had previously roughed out for the "Advanced" session.
- Numpy: if a particular groups project calls for it, we can address it in a focused instructor + single team session during the project time block in the second week.  We can of course mention it without going into detail (e.g., in libraries session)
- File processing [Py Adv. IO]: this is pretty much what I had in mind for the IO session.  They were familiar with csv format last year.  We might also add in some command line alternatives and discuss when to use which approach.  While that seems like a good backbone for the details they practice, probably also worth mentioning some of the other input / output options (both fs, and user peripherals)
- Python Libraries / Packages [Not Reinventing the Wheel]: I think of this as a blended session, more towards the engineering side of things.  This is about learning how to look for existing solutions to a problem, and evaluating how they match your specific context.
- Python Integration [Py + C++]: yes, but I think we should keep the plan to integration with a single other language.  In my mind, the goal here is using native bindings within a .py script, not providing more capable CL glue.  That's going to be up to the responsible instructor, however.
- Intro to SE [Overview], as per previous, in overview.
- Planning [Framing a Problem]: our experience last year was that the students needed encouragement to frame problems for themselves.  To me, that also covers development of requirements, and the planning aspect is less important than the framing part.  We can present the planning tasks (e.g., making issues) as part of the appropriate way to express the digested problem.
- Proj Dev and Comms [Team Communication via the Code...still working on this title]:  I think the important concept here is for the team to have a shared vocabulary baked into the thing they are building, so that people can work effectively in parallel and talk when together.  This naturally leads to discussion of good coding habits, agreeing upon style / standards, and at higher level setting up interfaces / APIs for individuals to implement against / within.  I'm not sure that pair programming is an effective technique for their skill level.
- Testing [Testing]: yes, we should address this as a topic.  I don't think the instructor for this session will be able to cover all of those items.  I think tests as expression of requirements, unit and regression testing, and how tests integrate with debugging are probably the most important items.  Try/catch/finally in my experience is about addressing errors outside the program logic (though it appears syntactically in some test frameworks).  It's worth mentioning, but I think we'll probably only be able to cover going after internal logic problems.
- Tools [Tools]: yep.
- OOP [Py OPP + Effective OOP]: I think this belongs in two parts, one the Python syntax, and two effective use of objects in design.  I'm a bit split as to the order on the day they are covered, but that can established probably as late as the day before.  UML: I think other than mentioning its existence, that this would prove a distraction.

Added sessions:
- Debugging: maybe should be Profiling + Debugging.  Anyway: I view it as a mixed skill about know where to check state (scope, what state to capture where, etc).
- User Interfaces: this is about imagining use cases for other people (including future self) and thinking about the appropriate vocabulary (at the command line, as part of some GUI, as a developer importing a library, etc) to make that person most effective
- Distributed Computing Sessions: distributed programming concepts (e.g., Map-Reduce) + syntax is a critical skill in most of the work I've done, so I figure its worth covering
- "Open" sessions: while perhaps not our best sessions last year, I think the students got a lot of being asked to think about what they wanted in a session

**Comment by tjhladish** [comment]
I edited the README for clarity ("fun basics" != fun basics) and completeness (e.g., adding missing warmup time slots).  Content wise, I'm fine with it as-is.

**Comment by tjhladish** [comment]
Although the scheduled "one instructor reboot meeting" is mysterious.  I didn't know how to re-word that one.

**Comment by jamrootz** [comment]
Could we call the first Friday PM session:
#include &lt;thewheel.h&gt;

**Comment by tjhladish** [comment]
Shouldn't that be "import thewheel", Dane?  Not as catchy, I know.

**Comment by jamrootz** [comment]
ah true, Python!

**Comment by seifu** [comment]
Does framing the problem include pseudocode? Is this the first time we introduce pseudocode? I'm curious what approach we have in mind for "framing the problem" specifically for Software Engineering (does a standardized approach exist)?

**Comment by arkerpay** [comment]
Courses I request to instruct:

Reuse
Framing the problem
Either OOP session

Courses I request to be backup on:

Either OOP session
Testing
Py Flow Control
Best practices

**Comment by pearsonca** [comment]
@seifu I think that may be the first place it comes up, though it may come up in a language session - @tjhladish is fond of pointing out that valid python can be written very much like pseudocode.  In my mind, it's also definitely in the Communication session, probably touched on again in Testing.

@tjhladish @jamrootz @dbmcpherson 

As @arkerpay already did - throw in your hats for session preferences (though I understand some are already marked, so you don't have much to do).  I'll add one aside: last year, we managed to keep most of the days from being all one instructor.  The ones that we didn't were pretty rough, so hopefully we can avoid that this year.

I've put myself down to do the Overview again, though most of that is getting the students out of their shells, so I'm not counting that against my three.

If we do the Parallel Computing version of the second Wednesday, I'd do either of those (not both).
Otherwise:
Framing a Problem
Debugging xor Testing [I think it's better different people lead these to provide alternative perspectives]
Tools
...or really most anything, frankly.  I'd be really excited about any of the sessions.

**Comment by seifu** [comment]
Other than the 2 Variables/Functions sessions I'm most interested in:

Debugging
Either OOP

I can be a general filler/support for anything the first week. And, I have not enough experience with Tue/Wed material for second week to lead (I can learn as necessary).

**Comment by dbmcpherson** [comment]
I can probably assist with framing the problem, debugging and OOP.
I should be able to learn I/O so long as we stick to csv files.

Additional comments would be to include brief intros of both instructors
and students in the day 1 warm up (unless that is already assumed to be
there) and on the day we have them learn about libraries, maybe we have
the warm up be a task where most will actually attempt to 'recreate the
wheel', then in the afternoon session which discusses libraries, we show
them the library that actually solves that task to drive home that
point.  We have command line tricks there now, so not sure if that could be
moved to another place.

**Comment by pearsonca** [comment]
I've slotted people relative to their expressed preferences.  We have a bit of duplication, the main conflicts being the OOP sessions.

I also think we need to ensure people are being spread evenly, not just for our stamina, but to make sure people are equally involved with the students early (or late) so that can usefully engage with them.
