### ISSUE TITLE
complete the testing session draft

### ISSUE THREAD

**Issue by pearsonca** [pearsonca/stdio-ghana#10]
content in

https://github.com/pearsonca/stdio-ghana/tree/gh-pages/sessions/2014/testing

**Comment by pearsonca** [comment]
@arkerpay on back up

**Comment by seifu** [comment]
@pearsonca might consider adding some text on groups of tests and testing in teams (really a subissue of the larger issue of coding in teams -- cute article here http://codesqueeze.com/what-your-dog-can-teach-you-about-building-teams/)

**Comment by pearsonca** [comment]
shifting into a polish issue.
