### ISSUE TITLE
Official Letter

### ISSUE THREAD

**Issue by seifu** [pearsonca/stdio-ghana#2]
Carl,
Please provide me with a document (by February 26th) for funding that contains the following:

Overall objective of the program
Brief (1-paragraph) history from last year
Course Dates
Estimated weekly time (from now until course) for my participation in planning curriculum/lessons
Contact information for program heads (here and in Ghana)

Thank You,
Seifu

**Comment by pearsonca** [comment]
draft out to Augie, he plans to have his edits back to me today / tomorrow, which should get it done within the next day or so.

**Comment by pearsonca** [comment]
Some delays, but should be getting signed version as a pdf today, which I'll pass on to you.  You can close ticket once you receive it.

**Comment by seifu** [comment]
The letter suits my needs. I'm closing the issue for that reason.

**Comment by SamuelAdusei** [comment]
Please would there by any STDIO course in Ghana this year. Can't wait for the second course period. Carl , Tom , Pearson.

**Comment by pearsonca** [comment]
@SamuelAdusei we are indeed planning the course now - this is the repository for the course materials.

The Univ. of Ghana Computer Science department should be putting out applications soon; if you want to get a jump, the application form is available at:

http://goo.gl/d68nbg

**Comment by SamuelAdusei** [comment]
Thank you
