### ISSUE TITLE
How does the instructor area work?

### ISSUE THREAD

**Issue by arkerpay** [pearsonca/stdio-ghana#29]
I created parker.md, but can't see it.  How do I see it?

**Comment by pearsonca** [comment]
Their collection implementation is currently in flux - don't work about the
exact implementation details, I'll figure out how to shoehorn the data
appropriately.

**Comment by arkerpay** [comment]
I tried moving files around on my local copy, but couldn't get it to work.
Don't worry, I only committed my photo and haven't pushed it yet.
